# Generated by Django 3.1 on 2020-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
